# Chapter 4 - Numpy Basic : Arrays and Vectorized Computation

In [2]:
import numpy as np

In [10]:
# Create an array
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is EC00-A5E6

 Directory of C:\Users\lenovo\Documents\Notes\file-learn\jupyter-notes

12/27/2022  03:25 PM    <DIR>          .
12/27/2022  03:25 PM    <DIR>          ..
12/27/2022  03:22 PM    <DIR>          .ipynb_checkpoints
12/27/2022  03:24 PM    <DIR>          Ch4-4.5
12/27/2022  03:13 PM           114,241 Ch4-Numpy Basic 4.1 NdArrays.ipynb
12/27/2022  03:21 PM             3,992 Ch4-Numpy Basic 4.2 Pseudorandom Number Generator.ipynb
12/27/2022  03:21 PM             6,901 Ch4-Numpy Basic 4.3 Unversal Function.ipynb
12/27/2022  03:21 PM            73,395 Ch4-Numpy Basic 4.4 Array-Oriented Programming.ipynb
12/27/2022  03:25 PM             1,318 Ch4-Numpy Basic 4.5 File Input and Output With Arrays.ipynb
               5 File(s)        199,847 bytes
               4 Dir(s)  220,706,394,112 bytes free


In [17]:
# save the file
np.save("Ch4-4.5/my_array_file",arr)

In [20]:
# load the array
np.load("Ch4-4.5/my_array_file.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Membuat array baru
arr_dua = np.arange(-10,1)
arr_dua

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

**Save multiple array**

In [24]:
# Save multiple array
np.savez("Ch4-4.5/archive_multiple_arry",a=arr,b=arr_dua)

In [34]:
# Load mutiple array
arr_arc = np.load("Ch4-4.5/archive_multiple_arry.npz")
arr_arc.__dict__

{'_files': ['a.npy', 'b.npy'],
 'files': ['a', 'b'],
 'allow_pickle': False,
 'pickle_kwargs': {'encoding': 'ASCII', 'fix_imports': True},
 'zip': <zipfile.ZipFile file=<_io.BufferedReader name='Ch4-4.5/archive_multiple_arry.npz'> mode='r'>,
 'f': <numpy.lib.npyio.BagObj at 0x1da5f744c10>,
 'fid': <_io.BufferedReader name='Ch4-4.5/archive_multiple_arry.npz'>}

In [36]:
arr_arc['a'], arr_arc['b']

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0]))

**Save array to compressed file** 

In [38]:
np.savez_compressed("Ch4-4.5/archine_compressed",satu=arr,dua=arr_dua)

In [39]:
type(arr_arc)

numpy.lib.npyio.NpzFile