# Chapter 4 - Numpy Basic : Arrays and Vectorized Computation

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

## Universal Function

In [69]:
# Create an nparray
arr = np.arange (10)

- Fungsi yang membutuhkan argumen array tunggal disebut dengan ***unary unversal function***
- Fungsi yang membutuhkan dua argumen array dan menghasilkan satu buah array tunggal disebut dengan ***binary universal function***

In [70]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [71]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [72]:
rs = np.random.default_rng(seed=42)
rsy = np.random.default_rng(seed=24)
x = rs.standard_normal(10)
y = rsy.standard_normal(10)
x, y

(array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
        -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393]),
 array([ 1.35074732,  0.34309058, -1.16299016, -0.18708582, -0.3394646 ,
        -0.22767632,  0.59685616, -1.27902314,  0.96665533, -1.12796069]))

In [73]:
# find maximum value
np.maximum(x,y)

array([ 1.35074732,  0.34309058,  0.7504512 ,  0.94056472, -0.3394646 ,
       -0.22767632,  0.59685616, -0.31624259,  0.96665533, -0.85304393])

In [74]:
# additional array
np.add(x,y)

array([ 1.6554644 , -0.69689352, -0.41253896,  0.75347889, -2.29049978,
       -1.52985583,  0.72469656, -1.59526573,  0.94985417, -1.98100462])

In [75]:
# modf, memecah bilangan pecahan dan bulat dari sebuah array
rs = np.random.default_rng(seed=42)
arr = rs.standard_normal(10) * 5
pecahan, bulat = np.modf(arr)
pecahan, bulat

(array([ 0.5235854 , -0.19992053,  0.75225598,  0.70282358, -0.75517594,
        -0.51089753,  0.63920202, -0.58121296, -0.08400579, -0.26521964]),
 array([ 1., -5.,  3.,  4., -9., -6.,  0., -1., -0., -4.]))

Argumen **out** pada ufunc

In [76]:
# Membuat array berisikan nilai 0
arr_zero = np.zeros(10)
arr_zero.astype(np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
# Membuat array dengan nilai urut
arr = np.arange(10)

In [78]:
# np.add dengan argumen out pada variable arrya arr_zero
np.add(arr,7,out=arr_zero)

array([ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.])

In [79]:
# nilai arr_zero mengikut output dari np.add diatas
arr_zero

array([ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.])