# Chapter 4 - Numpy Basic : Arrays and Vectorized Computation

In [1]:
import numpy as np

In [2]:
a = np.array([[2,2],[2,2]])
b = np.array([[2,2],[2,2]])

In [4]:
a@b

array([[8, 8],
       [8, 8]])

In [5]:
a.dot(b)

array([[8, 8],
       [8, 8]])

In [6]:
np.dot(a,b)

array([[8, 8],
       [8, 8]])

**Linear algabera module**

In [53]:
from numpy.linalg import inv, qr, det

In [59]:
x = np.array([[2,4,1],[2,6,2],[1,8,1]])
x

array([[2, 4, 1],
       [2, 6, 2],
       [1, 8, 1]])

In [86]:
inv(x)

array([[ 1.00000000e+00, -4.00000000e-01, -2.00000000e-01],
       [ 1.85037171e-17, -1.00000000e-01,  2.00000000e-01],
       [-1.00000000e+00,  1.20000000e+00, -4.00000000e-01]])

In [87]:
inv(x) @ x

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])

In [94]:
# Find determinan
determinan = np.round(det(x))
determinan

-10.0

In [112]:
# Find cofactor
determinan * inv(x).T

array([[-1.00000000e+01, -1.85037171e-16,  1.00000000e+01],
       [ 4.00000000e+00,  1.00000000e+00, -1.20000000e+01],
       [ 2.00000000e+00, -2.00000000e+00,  4.00000000e+00]])